version: '3.7'
services:
    service1:
        .....

    sdves-app:
        container_name: sdves-app
        build: ./sdves-app 
        ports:
            - "8000:80"
        labels:
            NAME: "sdves-app"
        networks:
            - app-network
     
    service2:
        ....

networks:
    app-network:
        driver: bridge
